name: Apollo Schema Check

# Generally running a pull_request_target with secrets from the fork is risky, however we are only using the schema.graphql
# file and not executing any code from the branch so it's safe here.
on:
  pull_request_target:
    branches:
      - main
    types: [opened, reopened, synchronize]
# .github/workflows/check.yml

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
#       APOLLO_VCS_REMOTE_URL: ${{ github.event.pull_request.head.repo.clone_url }}
#       APOLLO_VCS_BRANCH: ${{ github.event.pull_request.head.label }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      # only run this command with the `--background` flag if you have the Apollo Studio GitHub integration enabled on your repository
      - name: Run check against infratographer supergraph
        run: |
          rover subgraph check --name ipam-api --schema schema.graphql infratographer@main --background
